config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: {registrations:"registrations"}
root 'main#login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nombres,:apellidos,:celular,:email,:password,:password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:celular,:nombres,:apellidos])
  end

  end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_usuario!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  def new
    super
  end

  def create
    super
  end

  def update
    super
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GloryNiceShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <p class="navbar-text pull-right">
      <% if usuario_signed_in? %>
    Logged in as <strong><%= current_usuario.nombres %></strong>.
    <%= link_to 'Edit profile', edit_usuario_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_usuario_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Sign up", new_usuario_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_usuario_session_path, :class => 'navbar-link'  %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/main/login.html.erb
<h1>Main#login</h1>
<p>Find me in app/views/main/login.html.erb</p>